### ISSUE TITLE
Docker Compose Error: services.web.restart contains an invalid type, it should be a string

### ISSUE THREAD

**Issue by ShawnMercado** [MakUrSpace/mission-control#6]
OS:  Windows 11 / WSL Ubuntu
Python Ver:  3.10.12

I encountered an issue when trying to run `docker-compose up --build -d`  as instructed in the Readme.  The error message was:

```plaintext
ERROR: The Compose file './docker_compose/docker-compose.override.yml' is invalid because:
services.web.restart contains an invalid type, it should be a string
```

The `restart` field under the `web` service in my `docker-compose.override.yml` file was set to `no`, which is supposed to be a valid value I think:

```dockercompose
services:
  web:
    restart: no
```

However, the error message suggests that `no` is not being recognized as a string. Enclosing `no` in quotes seems to resolve the issue:

```dockercompose
services:
  web:
    restart: 'no'
```

I think "no" is a keyword in compose syntax?  Not sure.

**Comment by nate3D** [comment]
This will be addressed in [issue #5](https://github.com/MakUrSpace/mission-control/issues/5)
